### PR TITLE
Switch to expo notification for the timer of the Washing Machines

### PR DESCRIPTION
**Pull request by mdesautel**
This PR aims to transition from the CloudFunction system that was previously used (for sending a notification to the connected user when his locked machine was about to finish) to the expo-notification library, which is simpler of use and more appropriate for this kind of task. The former was originally used due to a confusion about the ability of the timer-related events to be managed entirely by frontend. When it was concluded that they indeed could, I first stayed with the CloudFunction because I had already started implementing it. So now comes the switch to expo-notification, which is a more coherent way of sending local notifications instead of push notifications, and that requires less interaction with the database. Hereafter is a summary of the main changes:

In WashingMachineScreen.tsx:

-First, the app needs to ask permissions to the user to send him notifications. A modal opens when he submits his choice of program duration, to prompt him for approval. If he refuses, nothing is sent and he can continue to use the machines normally. If he accepts, and the duration of the program is more han three minutes long (which will probably be the case), then we inform him when his cycle is about to finish (I figured out the user would want to have some time to go to the laundry room).

-As the initial computation of the timer takes a few instants, we need to ensure that only one scheduling happens. For that purpose, an attribute 'notificationScheduled' from the type LaundryMachine is used, and set to true at the first call to calculateTimer. This attribute is updated on Firebase to ensure that the updates are reflected promptly and correctly. We thus enter conditionally the scheduleFinishNotification method based on this attribute.

-When the machine has completed its cycle and it unlocked, or when the user cancels his program, then the attribute must be reset to 0, and the timers set cleaned, to ensure that the next person to use the machine also has a notification for his machine.

In NotificationWashingMachine.test.tsx:

This test suite checks if the permissions of the app reflect the user's choice, and if the triggering of the notification is made according to that. It then checks that nothing is triggered if the calculated duration is negative (i.e. if we are less than 3 minutes from the end of the cycle). Finally, it verifies that the attribute field 'notificationScheduled' is correctly updated in firebase (to ensure that multiple schedulings do not happen).
I mocked Timestamp, linear-gradient and Alert, that weren't supported by Jest, along with other usual methods and components.
Note: if you are using a setInterval method, you have to use fake timers in the beforeEach, and retrieve the normal timers in afterEach, otherwise you will get a warning that you are trying to access a jest component after it has been torn down.
image

Minor fix: In the types I had to update the import from Timestamp which was not the same one as the imports from the files that used it (for the estimatedFinishTime attribute, for example).

Let me know if you have any questions!

### CODE REVIEW

**Review by userdarius — APPROVED** [review]
Thanks a lot for this PR @MadelineDesautel I like that you paid attention to the UX for the user with the delay integration. The only small comment I have is that we should probably test and make sure the notification is still fired in the even the user goes offline as a precaution and maybe think of edge cases which could be problematic if a lot of users are updating the state of the washing machine in parallel. Also something I thought of is that although firestore uses offline persistence if another user updates the washing machine state while the device is offline, Firestore may overwrite local changes using its "last-write-wins" strategy which could be an issue. These are subjects for a separate PR though so I'll go ahead and approve the current changes so we can merge.

**Comment by mdesautel** [comment]
> Thanks a lot for this PR @MadelineDesautel I like that you paid attention to the UX for the user with the delay integration. The only small comment I have is that we should probably test and make sure the notification is still fired in the even the user goes offline as a precaution and maybe think of edge cases which could be problematic if a lot of users are updating the state of the washing machine in parallel. Also something I thought of is that although firestore uses offline persistence if another user updates the washing machine state while the device is offline, Firestore may overwrite local changes using its "last-write-wins" strategy which could be an issue. These are subjects for a separate PR though so I'll go ahead and approve the current changes so we can merge.

Yes this is part of my task for this week, I'll do another PR with this feature

**Comment by userdarius** [comment]
I actually discovered a bug yesterday on your branch where the timer seems to be sending a notification twice when the timer is scheduled. This should be a minor fix but ideally we could patch this before merging into main.

**Comment by mdesautel** [comment]
I pushed a fix for that, now the timer sets useRef to true before entering the scheduling method, and resets it to false after (sort of like a lock), so that it sees immediately when a notification is being sent. It only pushes once now. I also made some small changes to the cleanup and intervalIds, and made sure that the notification is shown also in foreground. Hereafter is a picture of the notification:
Capture d'écran 2024-12-12 171525
Capture d'écran 2024-12-12 135046

**Pull request merged**
