### PR TITLE
Feat/frontend-for-washing-machines

### PR DESCRIPTION
**Pull request by userdarius**
#### Summary

This PR introduces two new screens to manage and interact with laundry machines within a residence: `ManageMachinesScreen` for machine management and `WashingMachineScreen` for timer functionality. These screens allow users to view machine status, toggle maintenance, and set timers for laundry cycles. It is important to note that for now no distinction is made between what screen appears for tenants or landlords and the ManageMachinesScreen will only be visible for the landlord. Additionally the WashingMachineScreen will be visible for both.

#### Changes

1. **ManageMachinesScreen**:
   - **Fetching Machines**: Fetches and displays a list of laundry machines for a given residence from Firestore using `getAllLaundryMachines`.
   - **Add Machine**: Allows the addition of new laundry machines to Firestore. Input is validated to ensure the machine ID is not empty.
   - **Delete Machine**: Removes a machine from Firestore and updates the local state to reflect the change.
   - **Toggle Maintenance Status**: Allows toggling of the machine's maintenance status. Updates are synced with Firestore.
   - **UI Elements**: Provides a form for machine addition and displays a list of machines with status indicators for availability and functionality.

2. **WashingMachineScreen**:
   - **Timer Functionality**: Users can set a timer on available and functional machines, simulating a laundry cycle.
   - **Machine Status Display**: Displays a list of machines along with their availability and functionality status. Machines are shown as "Available," "In Use," "Functional," or "Under Maintenance" based on their state.
   - **Firestore Syncing Placeholder**: Includes a placeholder for syncing the timer with Firestore (`syncTimerWithFirestore`) to simulate backend functionality.
   - **UI Elements**: Includes a modal for timer setting and interactive buttons for each machine.

3. **Styling**:
   - Updated styling for machine status, availability, and buttons to enhance the user experience.
   - Added a consistent layout and style across both screens with customized colors and layout properties to highlight machine status (e.g., "Available" in green, "Under Maintenance" in red).

#### Testing
- Manually tested UI interactions to ensure the list of machines displays correctly, and actions like adding, deleting, and toggling maintenance status function as expected.
- Mocked Firestore interactions for adding, deleting, and updating machines to verify state management without actual Firestore changes. This is done manually for now in the screens page with fake machines but will need to be more thoroughly tested once the timer backend is implemented.

#### Notes
- Future iterations may include further integration with Firestore for real-time updates on machine availability and functionality.
- Placeholder functionality (`syncTimerWithFirestore`) will need to be replaced with actual cloud functions integration for timer syncing in a future update.

#### Screenshots (the data displayed are placeholders for now)
- **ManageMachinesScreen**: Shows the form for adding machines and list of machines with delete and toggle maintenance options.
Screenshot 2024-11-07 at 19 47 55

- **WashingMachineScreen**: Displays machine statuses and modal for setting timers.
Screenshot 2024-11-07 at 19 47 48

- **Add timer**: Opens up a modal to set a timer. (The styling and timer values to display need to be worked out based on cloud functions which @MadelineDesautel is working on atm)
Screenshot 2024-11-07 at 19 58 34

### CODE REVIEW

**Review by AdrienDeschenaux — CHANGES_REQUESTED** [review]
Hey Darius! thank you for your work, 

functionnaly speaking this works great! But I must say that I'm a bit puzzled. This does not follow the design we agreed together during previous week on in the Figma. 

I'm sorry to say that but I cannot merge this for now,  you should spend some time to make it look more like the Figma and then we can merge it into main.

**Review by mdesautel — CHANGES_REQUESTED** [review]
Hi, thank you for your PR, I tested the two screens in my app and it seems to work correctly. I think we will make the managing screen visible only to the landlord when we have two definite stacks for the types of user, which should be very soon because we start to have a meaningful side of the app for the landlord. A point that could maybe be revisited is the styling, notably the rounding of the buttons and maybe the color scheme which doesn't seem exactly like the rest of the app.
Also, since you created the getAllLaundryMachines in the firestore.ts, I think you can now replace your placeholders for the laundry machines in the list!
For the timer handling, I will indeed push the cloud function soon, so we can sync our work:)

**Comment by userdarius** [comment]
Thank you for the valuable comments. After implementing the basic frontend, a significant portion of the work shifted to synchronizing with the database, resulting in a reduction in time spent on design. However, it is important to note that this design was not intended to be final, as Figma remains the primary reference. My primary objective was to ensure that the frontend is flexible and adaptable to the backend.

I am awaiting the cloud function backend from @mdesautel to implement the timer modal, as its functionality heavily relies on the data format. I will make additional design adjustments tomorrow before we merge to main.

**Comment by userdarius** [comment]
Here is the updated styling changes for the washing machine feature screens. The changes include the addition of the washing machine icon, cleaner design as well as the use of reusable components for the timer setting button to match the figma design. Regarding the timer @MadelineDesautel will be merging her PR into main and we will combine both right after.

Screenshot 2024-11-09 at 18 15 21
Screenshot 2024-11-09 at 18 15 48

**Review by mdesautel — APPROVED** [review]
Hi, that is great that you could update the styling to be harmonious with the other parts of the app and the figma! I ran your branch on my phone and it works, I think it is just on my phone but some components don't render fully in the machine items (see picture), but that is fine because my PR contains changes that should fix that anyways.

Capture d’écran   2024-11-09 à 18 53 18

It is great also that you reused the submit button component, and that you updated it (because i guess it was designed at the beginning of the project so it wasn't fully adaptable then) so now we will be able to use this one more.

Regarding the merging with my backend, as we discussed earlier today I think it is better if we merge your PR first on main and then merge mine, because it is built on top of yours, but it shouldn't be a problem.

**Review by AdrienDeschenaux — APPROVED** [review]

**Pull request merged**
