### PR TITLE
New Figma designs and wireframes (no code)

### PR DESCRIPTION
**Pull request by mdesautel**
This PR is to show the new figma designs and wireframes, as suggested by the coaches. It does not contain any code to check, but it should probably be closed after my other PR to avoid any conflicts, because it reflects the unmerged changes in it.

The added designs are for the code generation and the landlord's list of issues.
image

The wireframes were made to reflect the current state of the design page of the figma, as per the M1 feedback recommendations.
image
image
image

### CODE REVIEW

**Comment by mdesautel** [comment]
(It mentions that four files were changed but they are the same ones as in the other PR I made earlier today)

**Comment by AdrienDeschenaux** [comment]
Hey! Thank you for your work, I like those designs, they are coherent with other screens of the app already on the figma (and implemented). I think on the code generation screen we could have a button allowing to directly generate for someone (and maybe later for a list of new tenants) and that would for example directly send the code by email (or sms) to all the new tenants from a residence. 

Let me know what you think about this idea!

**Review by AdrienDeschenaux — CHANGES_REQUESTED** [review]
Hey! Thank you for your work, I like those designs, they are coherent with other screens of the app already on the figma (and implemented). I think on the code generation screen we could have a button allowing to directly generate for someone (and maybe later for a list of new tenants) and that would for example directly send the code by email (or sms) to all the new tenants from a residence. 

Let me know what you think about this idea!

**Comment by mdesautel** [comment]
Yes, I added the tenant selection originally, it seems to not have been saved by figma so I'll re-add it along with the other functionalities you suggested!

IMG_8029

**Review by AdrienDeschenaux — APPROVED** [review]
Thanks for the changes, I'll merge this when Shin will have done the build for today's meeting just as a security measure (but since the code is the same as for the other PR this shouldn't be a problem) 
This will be closed right after the meeting!

**Pull request merged**
