### PR TITLE
Figma design for the situation report screen 

### PR DESCRIPTION
**Pull request by AdrienDeschenaux**
Hello Team! 

## Design proposition : 

This is my design proposition for the situation report screen.

<div style="display: flex; gap: 10px;">
  Image 1
  Image 2
</div>

## Design inspiration : 

My idea for this screen is following the situation report form used in my residence, I did not create the whole form in the figma but indeed the implementation should integrate all the fields. Here's bellow a picture of the situation report I took as a model : 
<div> 
  situationreportexample
</div>

As you may have noticed, for the end of the screen, an idea of implementation would be to integrate already implemented feature for the pictures such as : taking pictures, caching the picture for offline option and integrating the images carousel to allow user to take pictures of some elements. These feature could be added as a feature enhancement, I think it could be better to first have something to get user feedback from my landlord and ask him if this kind of feature would be interesting for him. I would like to have your opinion on this, please leave a comment to tell me what you think about this.

## Design enhancement and back-end integration 

As we already discussed during today's meeting, I think it's a good idea to start with a form with a simple situation report form and increment the functionalities over time. Here's some suggestion I have for the future improvement : 
- allow the landlord to create custom layout for the situation report. This is in my opinion a really important feature as a single situation report may not be meeting all the needs for any residence. (Maybe for example, FMEL use a specific form for Vortex and a different one for Triaude) 
- allow landlord to link a remark with a specific item in the list. For example if there is a remark about the item n° 2, the landlord could type `@1 myremark` and this would highlight the text and tapping on it would send directly to the item. This could be a really cool feature (maybe not easy to implement so we should leave it as an improvement if we have time for it)

One of the main problem of the back-end integration could be to find a structure that could be stored in the firebase database, as we think that it may not be possible to store a list of list of even tuples, we might need to come up with an other solution. 

## Next step

The next step once this design is approved, is to create and test a front-end for this screen using a hardcoded situation form, but keeping in mind that we would like to go with something that can be easily changed by the landlord, this mean creating components that can easily be adapted with respect to the database representation of a situation report layout.

### CODE REVIEW

**Comment by mahdiatallah** [comment]
Hi!

I really like the design, especially the fact that it's inspired by an actual situation report screen (mine was quite similar too). I also agree that we should gather user feedback regarding the potential addition of a camera feature. However, I have some remarks to share:

- The fields at the top (e.g., residence, apartment, arriving tenant, leaving tenant) are likely already known by the app's state, either through the tenant account or set up by the landlord when creating the situation report.
- Instead of displaying these fields, it might be better to use this space to explain the abbreviations, rather than having them written in a small font.

## Suggestion for the coming weeks
> One of the main challenges with back-end integration might be finding a structure that can be stored in the Firebase database. It seems that storing a list of lists or even tuples directly might not be supported.

After skimming through [Firebase Firestore Data Types Documentation](https://firebase.google.com/docs/firestore/manage-data/data-types), I noticed that we could potentially mimic tuples by using strings with delimiters or maps. 

This is just a suggestion, and although it’s not part of this week’s task, I wanted to bring it up as it might become relevant later.

**Comment by ShinUrech** [comment]
I really like the idea too! Can you give me more insight into how we would integrate that into the current flow of the app ? Other than that, i think the design is quite simple and intuitive. Great job!

**Comment by AdrienDeschenaux** [comment]
Hey, thank you for your feedbacks!

Here's how I think this would integrate in the flow of the app : 

1. The landlord goes on the screen through the drawer
2. He enter the residence name and the apartment id (as an enhancement, we could make the landlord access the situation report through the screen where he manages the residence and the apartments)
3. Fill the form with the relevant information 
4. (optional) take picture
5. (optional) add remarks

Concerning your remark about the input text fields for the name/surname, @mahdiatallah I think that might be a good idea to keep those information because, I don't think that we have at some point both the entering and leaving tenant. When they're in the residence, they are indeed in the database, but once they left they are removed therefore in my understanding of our current database, we can only have one tenant at a time and we could never have both at the same time, that's why I added those fields. Concerning the description of the meaning of the symbols, as you can see on the example of situation report I attached, those symbols are explained really quickly with only a small text as well, I don't think that describing in a big text would be a big improvement (The landlord would use regularly those forms and quickly become familiar with the labels and would not have much more benefit from having a big explanation on the screen).

Let me know what you think about this.

**Comment by ShinUrech** [comment]
Wouldnt it be easier to have a picker that allows the landlord to choose from which residence and appartements he is assigned to? I dont think that the landlord should remeber every residence ID and appartement ID in order to complete these tasks

**Comment by mahdiatallah** [comment]
If I understand correctly in thia scenario  it would be the job of the landlord to fill the form and not of the tenant?

**Comment by AdrienDeschenaux** [comment]
Yes, that's correct, the landlord fill the form and I think we may need to figure out a way for the tenant to approve the situation report (like adding the signature at the bottom of the situation report)

**Comment by AdrienDeschenaux** [comment]
> Wouldnt it be easier to have a picker that allows the landlord to choose from which residence and appartements he is assigned to? I dont think that the landlord should remeber every residence ID and appartement ID in order to complete these tasks

Yes indeed you're right I think that would be easier that way

**Review by mahdiatallah — APPROVED** [review]
Thanks for your contribution!

**Comment by ShinUrech** [comment]
After your modifications we can say that this PR is a...
great-success-yes
Approved ✅

**Review by ShinUrech — COMMENTED** [review]
After your modifications we can say that this PR is a... 
great-success-yes
Approved ✅

**Pull request merged**
